### ISSUE TITLE
Allow importing TEI XML

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/GrETEL-upload#2]

**Comment by oktaal** [comment]
Retokenize text and parse it, or reuse already tokenized text.
Include the metadata.

**Comment by oktaal** [comment]
The Python tool [TEI transformer](https://github.com/fizzbucket/tei_transformer) converts TEI to PDF (using Latex and lxml). That might be something to base a TEI reader on. 

There is also the more general application [PhiloLogic](https://github.com/ARTFL-Project/PhiloLogic5) database, search application for TEI which might also server as a source of inspiration. I'm still looking for some general usage library to work with TEI like the [pynlpl](https://github.com/proycon/pynlpl/tree/master/pynlpl) library I use for [folia2alpino](https://github.com/UUDigitalHumanitieslab/folia2alpino), but I couldn't find it yet.

Maybe it could be possible to try to add the TEI format to pynlpl? In that case the folia2alpino program could be made more general and also used for converting TEI.

Maybe additional meta information could be added on node level once this is available? E.g. a `ref` attribute or the surrounding tag (such as emphasis). Also consider how this would be dealt with in GrETEL and this might even entail changes to the Alpino format: https://github.com/UUDigitalHumanitieslab/gretel/issues/57

**Comment by mhkuu** [comment]
Hi @oktaal, you could look into [OpenConvert](http://openconvert.clarin.inl.nl/openconvert/web/help.html), that should allow conversion from TEI to FoLiA. But implementing something in pynlpl would also be nice as OpenConvert is Java-based.

**Comment by oktaal** [comment]
I could definitely "borrow" some of the OpenConvert code! I do think it's better not to introduce Java or OpenConvert itself to this project as well. The number of languages, tools, libraries and frameworks is already getting a bit out of hand. (And I don't really like Java anyway)
