### ISSUE TITLE
Allow importing FoLiA XML

### ISSUE THREAD

**Issue by mhkuu** [UUDigitalHumanitieslab/GrETEL-upload#3]
Possibly: also find a way to import metadata.

Documentation on FoLiA can be found via https://proycon.github.io/folia/

**Comment by oktaal** [comment]
Retokenize text and parse it, or reuse already tokenized text. Check whether Lassy XML is possible in FoLiA: no need to reparse that.

Include the metadata, document wide and per utterance.

**Comment by oktaal** [comment]
Within this issue: just parse the original text found in the XML (reusing the tokenization is probably pretty straightforward) and no more than that.

**Comment by oktaal** [comment]
Created separate Python package for performing this conversion: https://github.com/UUDigitalHumanitieslab/folia2alpino
